
mod_id=invcrafting
curse_id=232597
curse_slug=inventory-crafting-grid
mod_version=1.1.3
mod_name=invcrafting
mod_group_id=com.lothrazar.invcrafting
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=


flib_version=0.1.0
flib_file=8022223
