
mod_id=invcrafting
curse_id=232597
curse_slug=inventory-crafting-grid
mod_version=2.0.0
mod_name=invcrafting
mod_group_id=com.lothrazar.invcrafting
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=inventory-crafting-grid


flib_version=0.2.0
flib_file=8117455
